// TRY CATCH allows you to run a code whenever you receive an error.

try {
    console.logs("Hello world");
} catch(err) {
    console.log(`${err} : Error Received`);
}